### ISSUE TITLE
Bounding box på ikoner

### ISSUE THREAD

**Issue by formfett** [nrkno/core-icons#10]
VI ønsker oss en bounding box på alle ikonene så det blir enklere å bruke de i Sketch/Photoshop etc.
En firkant på 15x15px som fyller hele flaten, selv om selve ikonet ikke gjør det.

Google gjør det på denne måten:
```
<svg fill="#000000" height="24" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg">
    <path d="M0 0h24v24H0z" fill="none"/>
    <path d="M10.09 15.59L11.5 17l5-5-5-5-1.41 1.41L12.67 11H3v2h9.67l-2.58 2.59zM19 3H5c-1.11 0-2 .9-2 2v4h2V5h14v14H5v-4H3v4c0 1.1.89 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2z"/>
</svg>
```

**Comment by jorgeneidem** [comment]
Det Google gjør får å ha bounding box i sine material-ikoner er at de har har en path uten fill på feks 24x24. Kunne vi gjort det samme eller ødelegger det for noe? @eirikbacker 

![screen shot 2017-09-22 at 10 11 28](https://user-images.githubusercontent.com/4020663/30735297-c1d25cbc-9f7e-11e7-951b-ea77b9a0cfa5.jpg)

**Comment by eirikbacker** [comment]
@jorgeneidem yupp, slik som @formfett påpeker :) jeg har noe kode for å automatisere dette, men tenker vi burde potensielt ha en versjon med og uten ekstra path for å spare bytes hos sluttbruker?
Det vil være ca. ~5KB mer å laste boundingbox for alle ikoner i dag. Det er ikke mye, men det er mer enn hele `core-css` f.eks :)

**Comment by jorgeneidem** [comment]
Djises, ja ser nå at jeg skrev akkurat det samme som Magnus hadde skrevet. Man er virkelig langt fra 100% med fersk baby i heimen
