### ISSUE TITLE
add download all icons button

### ISSUE THREAD

**Issue by htor** [nrkno/core-icons#107]
add button to download a .zip containing all icons somewhere on the icon page

**Comment by eirikbacker** [comment]
Sounds good! Should have the same in `@nrk/core-fonts` :)
Regarding colors: this option is only important for iOS-developers, who are using PDF-versions of icons, and then ned to download them pre-colored. I don't know who submitted this request or usage context, but I assume only svg files are okay? But I'd like to know the use-case:
- Developers should use NPM/static.nrk.no to ensure getteing updates
- Designers should use sketch/figma library to ensure getteing updates

**Comment by htor** [comment]
closed by #108
