### ISSUE TITLE
Move icons with a NRK TV specific look to a alternative namespace

### ISSUE THREAD

**Issue by macbruker** [nrkno/core-icons#117]
Ever since core-icons was last updated, I have been thinking about the style influenced by the new NRK TV design. And I am not convinced that change was a good idea.

To me, the success of an icon set is all about a consistent style, combined with clear, easy to understand shapes and symbols. This isn't the case with some of the redesigned icons. 

![image](https://user-images.githubusercontent.com/1032194/70810584-57ad6b80-1dc4-11ea-81a9-e870201a5fba.png) It took a surprising amount of time before I realised this was the play button inside NRK Radio.

My main issue is with the new play icon, but I believe other icons have become less obvious as well. I do understand the need for NRK to strengthen the NRK TV brand, but I have serious doubts that the new icon style is solving this problem. And I can't see how the change is possible to measure in any meaningful way. As Luke Wroblewski puts it, _[obvious always wins](https://medium.com/google-design/the-obvious-ui-is-often-the-best-ui-7a25597d79fd)_. My two cent.

As an attempt to please everyone, I suggest keeping these icons as an alternate style that NRK TV can apply to their product, and bring back other icons as a more neutral style that suits other products better. 

I also suggest that we do another review of our icons, to ensure that they share a clear and consistent style across the whole set.

**Comment by eirikbacker** [comment]
Is the problem really grouping, or the play-button? :)
I think the current grouping (including media) is very good, but as stated before - maybe the play-icon itself can be a bit problematic (ref. https://nrk.workplace.com/groups/1441367842612360/permalink/2466291940119940/)

**Comment by macbruker** [comment]
The main issue is certainly, but not limited to, the play icon.

I believe all these icons should be the alternate version, not the main:
- nrk-media-play
- nrk-media-play--fail
- nrk-media-ffw
- nrk-media-rwd
- nrk-media-next
- nrk-media-previous
- nrk-broadcast
- nrk-heart
- nrk-heart--active
- nrk-latest-news
- nrk-latest-news--active
- nrk-search
- nrk-search--active

There is something about the angles and line endings that doesn't fit with the rest of the icons. 

Grouping probably isn't the right way to describe what I am looking for, so I've updated the title to better reflect my issue.

**Comment by eirikbacker** [comment]
Sounds like a continuation of the discussion here https://app.slack.com/client/T04MCF2QC/C0C4KG11N/thread/C0C4KG11N-1568294395.040400 before resolving as a issue with redesign in the repo? :)

**Comment by htor** [comment]
er enig at play-ikoner burde endres/tilbys i forskjellige varianter. men er denne en diskusjon vi skal ta videre her? hvis ikke lukker vi denne
