### ISSUE TITLE
Copy css - mangler svg data

### ISSUE THREAD

**Issue by ssaegrov** [nrkno/core-icons#122]
Når man bruker "Copy CSS" funksjonen på core/  så mangler svg koden.

For å reprodusere: 
1. https://static.nrk.no/core-icons/latest/index.html
2. Søk etter nrk-gallery
3. Trykk Copy CSS

**Resultat:** background: url('data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" style="width:1.5em;height:1.5em" focusable="false" aria-hidden="true"%3E%3Cuse xlink:href="%23nrk-gallery"%3E%3C/use%3E%3C/svg%3E') no-repeat center / contain;

**Forventet resultat:** background: url("data:image/svg+xml,%0A%3Csvg viewBox='0 0 24 24' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath fill='currentColor' fill-rule='evenodd' clip-rule='evenodd' d='M21 5H7V3h16v14h-2V5zm-4 4H3v10h14V9zM1 7v14h18V7H1zm14 5.5c0 .8284-.6716 1.5-1.5 1.5s-1.5-.6716-1.5-1.5.6716-1.5 1.5-1.5 1.5.6716 1.5 1.5z'/%3E%3Cpath fill='currentColor' fill-rule='evenodd' clip-rule='evenodd' d='M7.3995 14.8284L3.22792 19H3v-2.6005L7.3995 12l7 7h-2.8284l-4.1716-4.1716z'/%3E%3C/svg%3E") no-repeat center / contain;

**Comment by htor** [comment]
takk! fikset nå
