### ISSUE TITLE
Icon Request: Reorder

### ISSUE THREAD

**Issue by marve-s** [nrkno/core-icons#130]
Trenger dette ikonet i core for implementasjon.
Brukes til å endre rekkefølge på lister.

SVG lagt ved

[nrk-reorder.svg.zip](https://github.com/nrkno/core-icons/files/4573653/nrk-reorder.svg.zip)

**Comment by eirikbacker** [comment]
Ser dette godkjent ut for deg @formfett ? :)

**Comment by formfett** [comment]
Ser greit ut for meg. Jeg trodde vi allerede hadde den i Core 😬 @eirikbacker

**Comment by eirikbacker** [comment]
Hehe, nope - ingen reorder her :) https://static.nrk.no/core-icons/latest/
Men supert! da kan vi pushe - takk for raskt svar :)

**Comment by formfett** [comment]
Tenkte mer på Dropdown-icon. Ikke noe icon i Core, men tror vi har hatt det i TV sin Figma ganske lenge.

**Comment by eirikbacker** [comment]
Ah, dropdown issuet #131 - ikke denne :) men det som ligger i #131 ser greit ut? da merger vi den også :) Super om du går over TV sin Figma og ser at Core-icons inneholder det som gir mening derfra - der har du best oversikt og tilgang :)

**Comment by formfett** [comment]
Jeg jobber ikke i TV lenger 😉 men @henrik-mattsson (eller noen andre) sier sikkert ifra om det er noe fra TV sin Figma som de trenger ut i Core.

**Comment by marve-s** [comment]
Vi trenger dette ja, ber jo ikke om unødvendige icon requests
