### ISSUE TITLE
Icon Request: Picture-in-picture ikoner

### ISSUE THREAD

**Issue by susanneholgernes** [nrkno/core-icons#15]
Som kan brukes på tvers av plattformer. Både Enter Picture-in-picture og Exit Picture-in-picture ikon

**Comment by eirikbacker** [comment]
Superb Susanne :) I've spoken with Magnus, do you guys coordinate directly?

**Comment by eirikbacker** [comment]
Any updates on this @susanneholgernes and @formfett ? :)

**Comment by formfett** [comment]
Her er to ikoner.
[nrk-media-picture-in-picture.zip](https://github.com/nrkno/core-icons/files/1207144/nrk-media-picture-in-picture.zip)
