### ISSUE TITLE
Icon update: Airplay and FFW/RWD

### ISSUE THREAD

**Issue by simenmyklebust** [nrkno/core-icons#167]
FFW/RWD is updated with NRK Sans font.
Minor adjustment to Airplay icons for better size/format compared to other NRK icons and standard iOS Airplay icon.

Adjusted icons:
- nrk-media-airplay
- nrk-media-airplay-active
- nrk-media-ffw-15sec
- nrk-media-ffw-30sec
- nrk-media-rwd-15sec
- nrk-media-rwd-30sec

<s>.zip with svg files: [export_final.zip])</s>
Updated w. alignment fix: [export_final.zip](https://github.com/nrkno/core-icons/files/8603103/export_final.zip)

![airplay-adjustment](https://user-images.githubusercontent.com/92149482/166229468-39238a91-99f4-4a83-8141-92c79abdf477.png)

**Comment by stefanogden** [comment]
![ex](https://user-images.githubusercontent.com/37073705/166237781-18678dda-ef31-4152-93e8-1b6dcf8b7cf6.png)

FFW/RWD icons are aligned to half pixels, old ones are top aligned. Intentional?

**Comment by simenmyklebust** [comment]
@stefanogden Not intentional, only text that was supposed to change. Well spotted!
Updated zip: [export_final.zip](https://github.com/nrkno/core-icons/files/8603103/export_final.zip)
