### ISSUE TITLE
New NRK TV logo

### ISSUE THREAD

**Issue by stefanogden** [nrkno/core-icons#176]
New NRK TV logo with NRK Sans type. 
Replaces "nrk-logo-nrk-tv".

Add the following logo variants:

- nrk-logo-nrk-tv--boxed
- nrk-logo-nrk-tv--stacked
- nrk-logo-nrk-tv--small
- nrk-logo-nrk-tv--small-stacked
- nrk-logo-nrk-tv--small-boxed

**Issues:**
- <s>The new default TV logo is 2px wider than the old one. Consequences?</s> Risk is considered very low.
- <s>SVG files contain static hex codes for color fills. Possible to replace with links to tokens somehow? If not, what routine should be established to keep SVGs up to date?</s> Made into separate issue.

**Figma branch:**
https://www.figma.com/file/KXGJ6Qcdf8JAyRCoKV55If/branch/nh7VfDugGv3laaeteUCFci/NRK-Core-Icons?node-id=12%3A2

**Files:**

[All files in a zip: nrk-logo-nrk-tv.zip](https://github.com/nrkno/core-icons/files/8886864/nrk-logo-nrk-tv.zip)

nrk-logo-nrk-tv
![nrk-logo-nrk-tv](https://user-images.githubusercontent.com/37073705/173254677-6ecd3948-5bf3-41e6-927c-48b1d5ec24ac.svg)

nrk-logo-nrk-tv--small
![nrk-logo-nrk-tv--small](https://user-images.githubusercontent.com/37073705/173254673-e51a234a-179e-4f8b-9d20-49333395af13.svg)

nrk-logo-nrk-tv--boxed
![nrk-logo-nrk-tv--boxed](https://user-images.githubusercontent.com/37073705/173254672-d23814e7-815e-4581-ae57-33fecac6c787.svg)

nrk-logo-nrk-tv--small-boxed
![nrk-logo-nrk-tv--small-boxed](https://user-images.githubusercontent.com/37073705/173254674-693a79ba-6b42-4add-b2b5-0d4dc198e744.svg)

nrk-logo-nrk-tv--stacked
![nrk-logo-nrk-tv--stacked](https://user-images.githubusercontent.com/37073705/173254676-81790f94-e3a4-459f-9191-da52f759bcf3.svg)

nrk-logo-nrk-tv--small-stacked
![nrk-logo-nrk-tv--small-stacked](https://user-images.githubusercontent.com/37073705/173254675-25b36603-f25f-4ded-a549-4215637ef4bf.svg)

**Comment by asmundmatzow** [comment]
Unless there is a quick fix for linking the SVG colors to tokens, I suggest we roll it out like this for now. Maybe make that a separate issue?

Unless the 2px wider issue causes any problems somewhere? I guess the logo is also in use on the NRK.no front page, in the header an the NRK TV plugs
<img width="394" alt="Screenshot 2022-06-13 at 09 17 15" src="https://user-images.githubusercontent.com/7030680/173300008-185e06c5-94c6-4214-90ee-195080aca2a7.png">
<img width="548" alt="Screenshot 2022-06-13 at 09 17 25" src="https://user-images.githubusercontent.com/7030680/173300023-107a4f20-fc46-46ed-adaf-5aa66a025735.png">
.

**Comment by stefanogden** [comment]
2px wider discussed with @Isdoda, @henrik-mattsson, @hgjelseth. Risk is considered very low.
