### ISSUE TITLE
Some chrome extensions prevents svg-elements to be injected

### ISSUE THREAD

**Issue by akselnordal** [nrkno/core-icons#18]
Some chrome extensions, among others this https://chrome.google.com/webstore/detail/google-analytics-opt-out/fllaojicojecljbmefodhfapmkghcbnh, prevents svg-dom to be injected into the page (without errors).

This error can be reproduced on www.nrk.no using the above chrome extension

**Comment by eirikbacker** [comment]
Hi @akselnordal which other chrome extensions prevents svg injection? :)

**Comment by akselnordal** [comment]
@storstad's wife have an extension called "WalkMe Extension for ThermoFisher" which prevents injection as well (every refresh). Dunno what kind of extension that is..

**Comment by eirikbacker** [comment]
Closed by #24
