### ISSUE TITLE
new new-icon

### ISSUE THREAD

**Issue by Isdoda** [nrkno/core-icons#184]
**Do you have an svg icon file?**
Please upload this file as an attachment or name the upstream branch containing it.
![nrk-media-ny-txt](https://user-images.githubusercontent.com/14125035/184372387-70a9c82e-6b0f-4a45-a4e4-2754a8e27e76.svg)

**Is the icon file ready to be added to the library?**
 - It has been trimmed using a minifier like [SVGOMG](https://jakearchibald.github.io/svgomg/). (Lowest precision without visual degradation)
- It has fill-rule of `fill="currentColor"`
- It has no explicit width/height
- It has viewbox of `viewbox="0 0 24 24"`

**What is the name of the icon?**
Make sure the icon fits the naming convention of `nrk-category-name--state`

Jeg er usikker på navngivningen da denne ikke har en annen state enn nrk-media-ny, men må bare implementeres på en annen måte (derav bare én bindestrek til slutt)

**Additional context**

Dette bildet forsøker å illustrere forskjellen på nrk-media-ny (alt 1) og nrk-media-ny-txt (alt. 2). 
![image](https://user-images.githubusercontent.com/14125035/184372747-bdf8200e-79d3-42b3-b035-023b1ebd1eaa.png)

**Comment by marve-s** [comment]
Hvis den skal erstatte ikonet med sirkel (nrk-media-ny) vil det brekke hos Radio. "ny" uten sirkel bør da legges inn som et eget ikon så vi slipper justere om pr nå.

**Comment by marve-s** [comment]
After discussing with the developers we can do the change, fixing the circle behind when the new icon is pulled from the set, (I thought it would update automatically by default). 

Ergo, it’s a thumbs up from me to override the current icon if needed.

**Comment by stefanogden** [comment]
To prevent bloating, we'll replace the existing nrk-media-ny icon using the same name.

The change will only take effect when team devs update their core-icons. We'll warn them of the breaking change.
