### ISSUE TITLE
Added active version of the categories icon in figma 

### ISSUE THREAD

**Issue by ole-marius** [nrkno/core-icons#188]
Added active version of the categories icon in figma. We need a active state for the icon so we can show that categories are selected. The Icon will be used in the menu for NRK TV. 
https://www.figma.com/file/KXGJ6Qcdf8JAyRCoKV55If/branch/PryXGFhtTuNg4hbOVcdkHO/NRK-Core-Icons?node-id=12%3A1203

![image](https://user-images.githubusercontent.com/105197760/188879968-afb6377f-a029-4d58-a9ad-95b340d8e081.png)

**Comment by stefanogden** [comment]
@skjalgepalg description added ☝️

![category--active](https://user-images.githubusercontent.com/37073705/189303786-d1b4b850-3f09-438e-b656-e21f2281ca8f.svg)
