### ISSUE TITLE
Choosing bright colors makes UI invisible

### ISSUE THREAD

**Issue by jorgeneidem** [nrkno/core-icons#19]
If you
Choose color --> 255,255,255 
or any other bright color (light gray, etc) 
the UI for downloading SVG / PDF / Copy HTML becomes invisible (unless you hover)

![screen shot 2017-08-02 at 12 24 12](https://user-images.githubusercontent.com/4020663/28869613-9fb3ad6c-777d-11e7-87e7-668ea59241c6.jpg)

**Comment by eirikbacker** [comment]
Added luminosity-test, available in https://static.nrk.no/core-icons/latest/
