### ISSUE TITLE
Updated icons – Tilgjengelighet

### ISSUE THREAD

**Issue by simenmyklebust** [nrkno/core-icons#190]
Update to all five icons in "Tilgjengelighet"-group.

**What is the name of the icon?**
Same naming, replace icon.

**Additional context**
Icons approved by Håvard Gjelseth, Siri Antonsen and Kristoffer Lium.

![image](https://user-images.githubusercontent.com/92149482/191251763-5dbcdbc7-8b78-4eff-8b63-719170e74527.png)

![image](https://user-images.githubusercontent.com/92149482/191251843-026c1063-f1f2-4892-9108-7f554533a3c2.png)

![image](https://user-images.githubusercontent.com/92149482/191251870-552a25f7-bc38-43cf-ae11-ca7380861224.png)

SVG-files:
[export.zip](https://github.com/nrkno/core-icons/files/9607343/export.zip)

**Comment by stefanogden** [comment]
Checking in with Yr, @andorpandor and Radio @marve-svenningsen 

Any issues with this?

**Comment by marve-svenningsen** [comment]
All good, ship it

**Comment by stefanogden** [comment]
![nrk-tilgjengelighet-horbarhet](https://user-images.githubusercontent.com/37073705/193229167-07b1a0a7-8b8b-4315-9087-566b56559e46.svg)
![nrk-tilgjengelighet-lydtekst](https://user-images.githubusercontent.com/37073705/193229174-bc5e677e-7628-4abb-9b95-7080accf7d98.svg)
![nrk-tilgjengelighet-synstolking](https://user-images.githubusercontent.com/37073705/193229177-f31c4fc9-a91e-450b-a9f7-511e23813542.svg)
![nrk-tilgjengelighet-tegnspraak](https://user-images.githubusercontent.com/37073705/193229180-2b42ef35-2d66-415c-b147-14250fe45e9f.svg)
![nrk-tilgjengelighet](https://user-images.githubusercontent.com/37073705/193229182-79e4a001-24fa-4836-9f8f-9a82a48a5c50.svg)

**Comment by stefanogden** [comment]
Optimized with SVGOMG and manually cleaned, added currentColor fills.
