### ISSUE TITLE
Age limit icons

### ISSUE THREAD

**Issue by Isdoda** [nrkno/core-icons#191]
**Do you have an svg icon file?**
Please upload this file as an attachment or name the upstream branch containing it.

**Is the icon file ready to be added to the library?**
 - It has been trimmed using a minifier like [SVGOMG](https://jakearchibald.github.io/svgomg/). (Lowest precision without visual degradation)
- It has fill-rule of `fill="currentColor"`
- It has no explicit width/height
- It has viewbox of `viewbox="0 0 24 24"`

**What is the name of the icon?**
`nrk-media-agelimit-6`
`nrk-media-agelimit-9`
`nrk-media-agelimit-12`
`nrk-media-agelimit-18`
`nrk-media-agelimit-A`

**Additional context**

![nrk-media-agelimit-6](https://user-images.githubusercontent.com/14125035/191959756-63ca59cd-22eb-4a72-b744-9fd783e1e9ae.svg)
![nrk-media-agelimit-9](https://user-images.githubusercontent.com/14125035/191959760-7ab2552d-5eaf-4f7c-b27b-b12ce61c84a3.svg)
![nrk-media-agelimit-12](https://user-images.githubusercontent.com/14125035/191959761-0ab79cda-0419-4236-adcb-557634e2a659.svg)
![nrk-media-agelimit-15](https://user-images.githubusercontent.com/14125035/191959762-0d508187-f42f-45ed-99b0-a6b8cd99c9bb.svg)
![nrk-media-agelimit-18](https://user-images.githubusercontent.com/14125035/191959764-b4ce0ecf-1b41-4002-8336-a8c88458e842.svg)
![nrk-media-agelimit-A](https://user-images.githubusercontent.com/14125035/191959765-de3201e1-6989-4f16-b517-e8d502569978.svg)

**Comment by stefanogden** [comment]
![image](https://user-images.githubusercontent.com/37073705/193234249-33da5005-23db-4326-91a8-7df7b0e70581.png)

Overlapping points when outlining NRK Sans Variable. Removing them manually.

**Comment by stefanogden** [comment]
Guide to how to fix NRK Sans Variable outlines in Figma added to Figma library file.
https://www.figma.com/file/KXGJ6Qcdf8JAyRCoKV55If/NRK-Core-Icons?node-id=2616%3A70

![image](https://user-images.githubusercontent.com/37073705/193253522-79226ff7-918b-453d-be56-6b37ad877b34.png)

**Comment by stefanogden** [comment]
![nrk-media-agelimit-6](https://user-images.githubusercontent.com/37073705/193264131-4f20ebe7-ef37-49fd-a3b7-f2fdf318faba.svg)
![nrk-media-agelimit-9](https://user-images.githubusercontent.com/37073705/193264136-d4794f62-f962-47ae-98b0-5d89ece58546.svg)
![nrk-media-agelimit-12](https://user-images.githubusercontent.com/37073705/193264137-93319112-8b28-42dc-9c8c-ca4884006287.svg)
![nrk-media-agelimit-15](https://user-images.githubusercontent.com/37073705/193264140-5016f59b-d697-43ea-b826-3759fa767d10.svg)
![nrk-media-agelimit-18](https://user-images.githubusercontent.com/37073705/193264145-b21f0fe5-00f8-47a6-9745-f439598827b4.svg)
![nrk-media-agelimit-A](https://user-images.githubusercontent.com/37073705/193264147-0baeeba6-155e-4db1-82f4-f7d01fa98baa.svg)

Optimized with SVGOMG and manually cleaned, added currentColor fills.
