### ISSUE TITLE
Adjust icons: NRK TV I boks, NRK TV i boks optisk justert

### ISSUE THREAD

**Issue by mengeba** [nrkno/core-icons#192]
**Do you have an svg icon file?**
Please upload this file as an attachment or name the upstream branch containing it.
https://www.figma.com/file/KXGJ6Qcdf8JAyRCoKV55If/branch/RRVtYUmTha6Hx1ieFV2AgM/NRK-Core-Icons

**Is the icon file ready to be added to the library?**
 - It has been trimmed using a minifier like [SVGOMG](https://jakearchibald.github.io/svgomg/). (Lowest precision without visual degradation)
- It has fill-rule of `fill="currentColor"`
- It has no explicit width/height
- It has viewbox of `viewbox="0 0 24 24"`

**What is the name of the icon?**
Make sure the icon fits the naming convention of `nrk-category-name--state`
NRK TV i boks
NRK TV i boks optisk justert

**Additional context**
Justert boks for bedre padding på merker som har descendere.

**Comment by mengeba** [comment]
@hgjelseth gjør oppmerksom på endring i logo i boks i tilfelle dere har begynt å bruke den varianten noe sted. Dette er for å sikre bedre luft rundt de merkene som har descendere + supersymbolet.

**Comment by stefanogden** [comment]
![nrk-logo-nrk-tv--boxed](https://user-images.githubusercontent.com/37073705/193284068-f336d1a0-236e-458e-9d1f-2a44c7fa14ca.svg)
![nrk-logo-nrk-tv--small-boxed](https://user-images.githubusercontent.com/37073705/193284071-37ebe21a-b135-4622-b67c-fbaff733da70.svg)

Optimized with SVGOMG and manually cleaned. Boxes do not conform to pixel edges.

**Comment by stefanogden** [comment]
![nrk-logo-nrk-tv--boxed](https://user-images.githubusercontent.com/37073705/193292067-513b3c1c-ff88-4c74-a6c1-d7617baf5e04.svg)
![nrk-logo-nrk-tv--small-boxed](https://user-images.githubusercontent.com/37073705/193292076-8ed8c532-70d3-4b54-a9f5-11031953fa5e.svg)

Optimized with SVGOMG and manually cleaned. Boxes do not conform to nearest pixel edge.

**Comment by mengeba** [comment]
hei alle logoene gås over nå I forbindelse med utrulling radio, også denne til nrk tv så de går opp i pixel. skal jeg kopiere det inn i en ny branch? jeg har ikke helt fått tak på systemet her i git hub så jeg kjenner jeg mister litt oversikten :)

**Comment by stefanogden** [comment]
Hei @mengeba, du kan bare lage en ny branch på det i Figma og en ny issue på det her i GitHub.

Men da tolker jeg det som at endringene i akkurat dette issuet ikke er nødvendige og kan slettes mens vi venter på det nye?
