### ISSUE TITLE
Icon Request: Lock/padlock (hengelås) 

### ISSUE THREAD

**Issue by jorgeneidem** [nrkno/core-icons#20]
We need an icon for locked content that user can't access when parent control is activated.

Probably useful for other stuff as well.

**Comment by jorgeneidem** [comment]
I made this and I think it's GREAT:
![nrk-lock-b](https://user-images.githubusercontent.com/4020663/28869974-e8202872-777e-11e7-8c1b-e18c6c0f3be1.png)

**Comment by eirikbacker** [comment]
It is GREAT. Do you have it as an SVG file @jorgeneidem? Any comments on the design @formfett?

**Comment by jorgeneidem** [comment]
Lock made.
