### ISSUE TITLE
New expressive icons

### ISSUE THREAD

**Issue by stefanogden** [nrkno/core-icons#201]
Adding  
[expressive_icons.zip](https://github.com/nrkno/core-icons/files/10812464/expressive_icons.zip)
[expressive_icons_2.zip](https://github.com/nrkno/core-icons/files/10815438/expressive_icons_2.zip)

<img width="1047" alt="image" src="https://user-images.githubusercontent.com/37073705/220881493-c6ae6208-d624-4fd7-afd2-3c10e7740e12.png">

New misc, arrows, chevrons and user categories in rounded style for younger age segment (expressive).

Used svgomg and replaced colors with currentColor.

Used "nrk-expressive" as prefix. 

Figma branch:
https://www.figma.com/file/KXGJ6Qcdf8JAyRCoKV55If/branch/k1v7KA5nhH2T2G3g6YZN92/NRK-Core-Icons?node-id=12%3A2&t=TQSiGYeY5Uqsu3Ao-1

**Comment by stefanogden** [comment]
Added expressive_icons_2.zip with 50 more icons.

**Comment by simenmyklebust** [comment]
Tror dere vi klarer å få ut hele settet med "nrk-expressive" snart, uavhengig av lisensendringer? Vi skulle gjerne tilgjengeliggjort det for utviklerne sånn at de kan komme i gang med å teste bruk av disse runde ikonene for barn i NRK TV.

**Comment by asmundmatzow** [comment]
> Tror dere vi klarer å få ut hele settet med "nrk-expressive" snart, uavhengig av lisensendringer? Vi skulle gjerne tilgjengeliggjort det for utviklerne sånn at de kan komme i gang med å teste bruk av disse runde ikonene for barn i NRK TV.

Ja, jeg mener at eventuelle lisensendringer ikke skal stå i veien for å få ut "nrk-expressive". De har ikke den samme problematikken som er knyttet til de nye logoene – der er det mulig vi må få avklart lisensendringer før vi publiserer endelig.
