### ISSUE TITLE
New media icons for NRK TV

### ISSUE THREAD

**Issue by skjalgepalg** [nrkno/core-icons#203]
(copied/moved from https://github.com/nrkno/core-design/issues/42 by @simenmyklebust)

**Do you have an svg icon file?**
[3x_media-icons_nrktv.zip](https://github.com/nrkno/core-icons/files/11079156/3x_media-icons_nrktv.zip)

**Is the icon file ready to be added to the library?**

- [x] It has been trimmed using a minifier like [SVGOMG](https://jakearchibald.github.io/svgomg/). (Lowest precision without visual degradation)
- [x] It has fill-rule of `fill="currentColor"`
- [x] It has no explicit width/height
- [x] It has viewbox of `viewbox="0 0 24 24"`

**What is the name of the icon?**
* `nrk-media-jump-to`
* `nrk-media-direkte-golive`
* `nrk-media-direkte-notlive`

**Additional context**
Three new icons used for media playback in NRK TV.
Used, tested and implemented in NRK TV.

* `nrk-media-jump-to` is used for navigating within the live buffer and browsing indexpoints
* `nrk-media-direkte-golive` is used for interactions that take the user to live playback (also focus-state of "direkte-notlive")
* `nrk-media-direkte-notlive` is used to indicate that the user isn't watching live

<img width="463" alt="live-icons" src="https://user-images.githubusercontent.com/92149482/227919963-d7be5580-1745-4458-b636-b74a8cff2078.png">

**Comment by simenmyklebust** [comment]
> @simenmyklebust eksisterer det en avrundet variant av `nrk-media-jump-to` som vi kunne lagt til som expressive variant?

@skjalgepalg 
Her er svg for `-expressive` versjon. Litt usikker på hva dere skrur av og på i SVGOMG for å få den så lett som mulig uten å endre utseende, så overlater det til dere:)

![nrk-media-jump-to-expressive](https://user-images.githubusercontent.com/92149482/231388181-753490a0-1415-43bd-9719-f36df12d9849.svg)
