### ISSUE TITLE
Conform height of bounding box across logo variants

### ISSUE THREAD

**Issue by asmundmatzow** [nrkno/core-icons#213]
Differently sized bounding box heights for different logos are causing issues for NRK Radio.

A possible fix could be to conform the height of the logo bounding box for the different `layout`-variants. The height would have to accommodate for the maximum logo height. This would mean:
* `title right: 20px` 1)
* `title below: 34px` 2)
* `with-bg: 24px`

1. This would accommodate for ascenders/descenders and most diacritics. A notable exception would the uppercase Å – this would have to be tweaked to fit the bounding box.
2. This would not accommodate for two-line titles (such as "NRK Kringkastingsorkestret"), which would need `title-below: 51px`. I would assume that it is better to operate with two heights – for one-line and for two-line titles, but this can be discussed further. The obvious case for these (besides "NRK Kringkastingsorkestret") would be NRKs districts, for example "NRK Vestfold og Telemark".

**Comment by asmundmatzow** [comment]
If we decide to implement this change, it should probably be done so that it is part of [PR #210](https://github.com/nrkno/core-icons/pull/210), which moves new logos from `nrk-logo-preview` to `nrk-logo`.

**Comment by skjalgepalg** [comment]
Added a codepen with examples to try and illustrate the issues with different bounding-box/viewbox sizes across same logo group types. https://codepen.io/skjalgepalg/full/rNqgpyv

**Comment by asmundmatzow** [comment]
After some discussion we propose to change the height of the bounding box to `24px` for `title-right` logos. This corresponds to the safe zone of logo composition, and is also equal to the `with-bg` logos, thus simplifying the structure a bit more. It will also address any potential issues with extra high/low ascenders/descenders, such as an uppercase Å.

**Comment by asmundmatzow** [comment]
One further question – if we include the safe zone of the logos for the title-right logos, should we not also do that for the title-below logos, so that that different variants behave in a internally predictable way?

This is the design guidelines for logo lockups and safe zones:
![Merkesystem-2](https://github.com/nrkno/core-icons/assets/7030680/f392c74f-a4b2-4f12-b602-e3321c1a1c08)

This is the adjusted Figma assets for `title-right`, and `with-bg`:
![Screenshot 2023-06-12 at 14 34 18](https://github.com/nrkno/core-icons/assets/7030680/e7123f30-a6e0-4d4d-8c59-3a19b82a0071) ![Screenshot 2023-06-12 at 14 34 05](https://github.com/nrkno/core-icons/assets/7030680/71f492a9-730f-4176-ad05-fec9da26a894)


This is the current Figma asset for a `title-below` logo:
![Screenshot 2023-06-12 at 14 33 50](https://github.com/nrkno/core-icons/assets/7030680/817c0d2e-213a-463a-8f5d-33d5fc6da753)

This would be an adjusted Figma asset (including vertical safe zone) for a `title-below` logo:
![Screenshot 2023-06-12 at 14 33 33](https://github.com/nrkno/core-icons/assets/7030680/966f4e5c-e5fa-4943-8529-4033e6c3a751)

**Comment by asmundmatzow** [comment]
Closing this issue as resolved.
In v13 all title-right/with-bg variants have the same height (`24 px`) while title-below logos that follow the standard logo lockup have a height of `41 px`.
Expceptions include: "NRK" logo (`h: 14 px`), title-below logos connected to P3/MP3. Title-below logo for "NRK Kringkastingsorkestret" (`58px`) where sub-brand is split into two lines. "NRK Yr", "NRK Nyheter", "NRK Sport", "NRK 1", "NRK 2" and "NRK 3", where logos have not yet been updated to new design (new versions are available in the ´preview´context).
