### ISSUE TITLE
Add duotone variants

### ISSUE THREAD

**Issue by asmundmatzow** [nrkno/core-icons#218]
Some icons feature a duotone variant. For these icons this should be available both for the default and `expressive`variant of the icon. 
We propose adding a separate `duotone` property to allow for this. Giving potential `nrk-[icon name]-duotone` or `nrk-[icon name]-duotone-expressive` variants.

**Comment by simenmyklebust** [comment]
Ser (fra designernes ståsted) ikke behov for å legge til "duotone" som en identifier. Det å legge elementer i ikonet som 50% opacity er sånn jeg leser det mer et visuelt virkemiddel vi har for å fremheve det aller viktigste i ikonet uten at det egentlig er noen logikk for når og hvilke ikoner som benytter seg av dette. 

Noen ganger kan elementet i 50% opacity være en god støtte til hovedelement i ikonet eller hjelpe på å balansere ikonet bedre, så er som sagt ikke slik at dette er en gruppe med ikoner som har noen logikk bak bruken av "duotone".

Hvis man står mellom to versjoner av ett og samme ikon (hvor ett benytter seg av 50% opacity på ett av elementene og det andre ikke), så tenker jeg at man aller helst skal ta et valg om hvilket som gjør jobben best og ikke beholde begge med "duotone" som en variabel.
