### ISSUE TITLE
New icon: Radio package

### ISSUE THREAD

**Issue by marve-svenningsen** [nrkno/core-icons#229]
## New icon request

If you are submitting several, just duplicate lines where applicable

**What is the name of the icon?**

Make sure the icon fits the naming convention of `nrk-category-name-variant--state`.

nrk-arrow-nested-expressive.svg
nrk-alarm-clock-expressive.svg
nrk-alarm-clock.svg
nrk-arrange-list-expressive.svg
nrk-arrange-list.svg
nrk-arrow-nested.svg
nrk-bullet-square-expressive.svg
nrk-bullet-square.svg
nrk-bulleted-list-expressive.svg
nrk-bulleted-list.svg
nrk-clock-expressive.svg
nrk-clock.svg
nrk-dialogue-expressive.svg
nrk-dialogue.svg
nrk-edit-expressive.svg
nrk-hardware-camera-expressive.svg
nrk-hardware-computer-expressive.svg
nrk-hardware-game-expressive.svg
nrk-hardware-headphones-expressive.svg
nrk-hardware-headphones.svg
nrk-hardware-laptop-expressive.svg
nrk-hardware-microphone-expressive.svg
nrk-hardware-microphone.svg
nrk-hardware-printer-expressive.svg
nrk-hardware-radio-expressive.svg
nrk-hardware-smart-speaker-expressive.svg
nrk-hardware-smart-watch-expressive.svg
nrk-hardware-speaker-expressive.svg
nrk-hardware-tablet-expressive.svg
nrk-hardware-tv-expressive.svg
nrk-hardware-watch-expressive.svg
nrk-list-expressive--active.svg
nrk-list--active.svg
nrk-list-expressive.svg
nrk-list.svg
nrk-media--complete-expressive.svg
nrk-media--complete.svg
nrk-media--not-complete-expressive.svg
nrk-media--not-complete.svg
nrk-media-beam-note-expressive.svg
nrk-media-beam-note.svg
nrk-media-direkte-animated--active.svg
nrk-media-direkte-golive.svg
nrk-media-direkte-notlive.svg
nrk-media-index-quaver-tiny-expressive.svg
nrk-media-index-quaver-tiny.svg
nrk-media-playlist-add-expressive.svg
nrk-media-playlist-add-later-expressive.svg
nrk-media-playlist-add-later.svg
nrk-media-playlist-add-next-expressive.svg
nrk-media-playlist-add-next.svg
nrk-media-playlist-add.svg
nrk-media-playlist-added-expressive.svg
nrk-media-playlist-added.svg
nrk-media-playlist-expressive.svg
nrk-media-playlist-remove-expressive.svg
nrk-media-playlist-remove.svg
nrk-media-playlist.svg
nrk-media-quaver-expressive--active.svg
nrk-media-quaver--active.svg
nrk-media-quaver-off-expressive.svg
nrk-media-quaver-off.svg
nrk-media-quaver-expressive.svg
nrk-media-quaver.svg
nrk-media-speed-0.8x.svg
nrk-media-speed-1.5x.svg
nrk-media-speed-1.25x.svg
nrk-media-speed-1x.svg
nrk-media-speed-2x.svg
nrk-new-chat-expressive.svg
nrk-new-chat.svg
nrk-progress-expressive.svg
nrk-progress.svg
nrk-refresh-expressive.svg
nrk-refresh.svg
nrk-reorder-expressive.svg
nrk-reorder.svg
nrk-rotate-expressive.svg
nrk-rotate.svg
nrk-sleep-expressive.svg
nrk-sleep.svg
nrk-some-tommelned-expressive--active.svg
nrk-some-tommelned-expressive.svg
nrk-some-tommelopp-expressive--active.svg
nrk-some-tommelopp-expressive.svg

**Do you have an svg icon file?**

Added zip
[icons.zip](https://github.com/nrkno/core-icons/files/12452661/icons.zip)

**Is the icon file ready to be added to the library?**

- [ ] It has fill-rule of `fill="currentColor"`
- [ ] It has no fill-rules with explicit color values like `fill="#f0f0f0"`
red fill on nrk-media-direkte-animated--active
- [ ] It has been trimmed using a minifier like [SVGOMG](https://jakearchibald.github.io/svgomg/). (Lowest precision without visual degradation)
- [ ] It has viewbox of `viewbox="0 0 24 24"` (except logos)
- [ ] It has no explicit width/height
"nrk-media-speed..." have set width for "category". Possible to set width to icon shape, keeping 24height.
Also, small icon versions added where scale isn't sufficient (nrk-media-index-quaver-tiny)

**Additional context**
Added expressive versions of all additional icons.

**Comment by marve-svenningsen** [comment]
@simenmyklebust @Isdoda 
Please have a look at the expressive versions, some are direct translations.

**Comment by simenmyklebust** [comment]
På 'nrk-media-playlist-add-next' og 'nrk-media-playlist-add-later' ville jeg forsøkt å strekke pila litt mer (la ytterpunktene på pilhodet gå litt lengre ut) for å få mer synlig luft mellom stammen og under pilhodet. Tror jeg lot 'expressive'-varianter få lov til å strekke seg litt lengre da jeg jobbet med de for TV for at de ikke skulle gro.

På 'nrk-plus' ser det ut som det har dukket opp en tredje variant ved en feil (variant3).

Likte 'nrk-hardware-game' 🤩
