### ISSUE TITLE
nrk-lock icon seems misaligned

### ISSUE THREAD

**Issue by haakemon** [nrkno/core-icons#261]
The lock icon has more spacing on top than bottom, and it makes the icon look misaligned in some cases. 
![image (1)](https://github.com/nrkno/core-icons/assets/2082481/76e112cb-921a-4e51-8d11-d2b2c8fc5b28)

<details>
<summary>Zoomed in view of the icon</summary>

![image](https://github.com/nrkno/core-icons/assets/2082481/aa97010c-170b-417d-acf1-db55bd1f8cc5)

</details>

The icon used in Figma has switched the spacing - more spacing on bottom than top:
![image (2)](https://github.com/nrkno/core-icons/assets/2082481/f6b7cdac-d3b5-45fb-a46c-09658e771b25)

This is unfortunate because then the sketches will not match the implementation. I dont know the connection between the core-icons package and the icons used in figma, are they coming from the same source?

Could we realign the icons in core-icons package, and make it the same as the figma icon (more space on bottom than top)?

[Slack thread reference](https://nrk.slack.com/archives/C49CY4VTP/p1704805213184809)

This also is an issue for the other lock-variations.

**Comment by stefanogden** [comment]
@marve-svenningsen, @simenmyklebust

Thoughts?
