### ISSUE TITLE
DK-logos oppdatert i Figma

### ISSUE THREAD

**Issue by mengeba** [nrkno/core-icons#265]
[Figma fil](https://www.figma.com/file/KXGJ6Qcdf8JAyRCoKV55If/NRK-Core-Icons?type=design&node-id=4765%3A69&mode=design&t=rZlAVpxaINk70jUO-1) er oppdatert, flyttet nye DK-logos fra preview til logo: 

- NRK Finnmark
- NRK Troms
- NRK Buskerud
- NRK Stor-Oslo
- NRK Østfold

fjernet de som ikke er gjeldende lenger: 

- NRK Troms og Finnmark
- NRK Oslo og Viken

**Comment by skjalgepalg** [comment]
Preview-ikoner må flyttes fra preview til logo -mappe og formodentlig kvernes gjennom svgomg.
Som nevnt over må ikke lenger gyldige ikoner fjernes fra logo -mappen

Endringen konsituerer en breaking change (major release av pakken) da vi fjerner to logoer
