### ISSUE TITLE
Updated icons: nrk-lock (+variants)

### ISSUE THREAD

**Issue by simenmyklebust** [nrkno/core-icons#274]
Updated nrk-lock icons based on request in  #261 
Fixes #261 

**nrk-lock + variants**

Make sure the icon fits the naming convention of `nrk-category-name-variant--state`.

- icon name is: `nrk-lock.svg`
- icon name is: `nrk-lock-expressive.svg`

- icon name is: `nrk-lock--active.svg`
- icon name is: `nrk-lock-expressive--active.svg`

- icon name is: `nrk-unlock.svg`
- icon name is: `nrk-unlock-expressive.svg`

- icon name is: `nrk-unlock--active.svg`
- icon name is: `nrk-unlock-expressive--active.svg`

**Do you have an svg icon file?**

[nrk-lock-icon_final.zip](https://github.com/nrkno/core-icons/files/14434207/nrk-lock-icon_final.zip)

**Is the icon file ready to be added to the library?**

- [x] It has fill-rule of `fill="currentColor"`
- [x] It has no fill-rules with explicit color values like `fill="#f0f0f0"`
- [x] It has been trimmed using a minifier like [SVGOMG](https://jakearchibald.github.io/svgomg/). (Lowest precision without visual degradation)
- [x] It has viewbox of `viewBox="0 0 24 24"` (except logos)
- [x] It has no explicit width/height

**Comment by Isdoda** [comment]
Kanskje du kan ta inn disse ikonene @haakemon? Det er ingen som eier repoet lenger
