### ISSUE TITLE
Icon Request: Icon that links to nrk.no

### ISSUE THREAD

**Issue by MKEshaswini** [nrkno/core-icons#32]
We need an icon that represents the link back to `nrk.no` from https://tv.nrk.no/ . Please find the attached screenshot for reference:

![image](https://user-images.githubusercontent.com/17903388/33266561-61e277e8-d376-11e7-8f27-9bff80909c3d.png)

**Comment by eirikbacker** [comment]
Hi @MKEshaswini - are you refering to the arrow?  the text NRK.NO should be text :) @formfett Maybe `nrk-arrow-left` could be used here in place of todays arrow? :)

**Comment by MKEshaswini** [comment]
Hi @eirikbacker  - yes it can be that NRK.NO shall remain as text and an icon for arrow :)
