### ISSUE TITLE
Upgrade core-docs

### ISSUE THREAD

**Issue by skjalgepalg** [nrkno/core-icons#320]
* Upgrade npm deps for core-docs
* Create release for core-docs
* Bump version used in core-icons
* Piggy-back on other issues' release to static

Optional:
Consider if core-docs is something to keep moving forward. If not sunset and archive accordingly.

**Comment by DervoDev** [comment]
core-icons bruker static versjon av core-docs. 
Kan derfor ikke bumpe versjon brukt. 

tatisk versjon av core-docs lansert på:
https://static.nrk.no/core-docs/4.0.5/index.html
