### ISSUE TITLE
Icon request: Hamburger menu

### ISSUE THREAD

**Issue by MKEshaswini** [nrkno/core-icons#34]
We need an icon for hamburger menu to be used in header for small screen sizes

**Comment by eirikbacker** [comment]
Hi @MKEshaswini ! This has been requested and discussed previously as well. As the hamburger-menu-pattern is something we want to gradually move away from, the conclusion for now has been to not include it in `core-icons`, but instead implement in the cases where needed. So, to achieve the vector icon as a background, please use the following code in your css :)
```
background: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 20 14'%3E%3Cpath fill='%23fff' d='M0 0h20v2H0V0zm0 6h20v2H0V6zm0 6h20v2H0v-2z'/%3E%3C/svg%3E") 50%/21px no-repeat;
```

**Comment by MKEshaswini** [comment]
Hi @eirikbacker , thank you for the update! I shall use the code :)
