### ISSUE TITLE
Adjust some logotypes

### ISSUE THREAD

**Issue by formfett** [nrkno/core-icons#36]
Jeg har justert størrelsen på noen logoer, P3, Mp3, NRK Super ++ slik at de matcher de andre logoene.

De har vært gjennom svg-optimizer og currentColor og font-size em er lagt inn.
Har du mulighet til å få de inn, Eirik?

[03 logojustering.zip](https://github.com/nrkno/core-icons/files/1575306/03.logojustering.zip)

**Comment by eirikbacker** [comment]
Looks very good @formfett 👍  I've adjusted the icons to use viewBox instead of with/height (I guess svgo did a change there) (see branch `feature/align`). Should also the `nrk-logo-nrk-mp3` be adjusted as this is the only odd one out now? :)

**Comment by formfett** [comment]
Here is `nrk-logo-nrk-mp3`, with viewBox 👍 
[nrk-logo-nrk-mp3.svg.zip](https://github.com/nrkno/core-icons/files/1591015/nrk-logo-nrk-mp3.svg.zip)
