### ISSUE TITLE
Typo and unclear info in Getting Started

### ISSUE THREAD

**Issue by jorgeneidem** [nrkno/core-icons#38]
«Automatically» is misspelled in Getting Started on https://static.nrk.no/core-icons/latest/index.html

Also, the NB text about scaling icons with font-size is a bit unclear. I'm not sure what it means, as default html code for using core-icons don't have anything to do with font size. I understand that you can set icons to scale with the body font size but still this sentence is a bit confusing.

![core-icons-typo](https://user-images.githubusercontent.com/4020663/37907784-6114dd9a-3106-11e8-82be-82f1a643b270.jpg)

**Comment by eirikbacker** [comment]
Hi and thanks! Will fix typo as soon as new static.nrk.no upload is running again :) Regarding `font-size` - setting `font-size: 10px` to the actual svg (for instance `.my-button svg { font-size: 10px }` ) will ensure the best rendering. Maybe just adding such an example is sufficient? Please let me know what you think about the formulation @jorgeneidem :)

**Comment by jorgeneidem** [comment]
Great!

**Comment by eirikbacker** [comment]
Resolved by #40
