### ISSUE TITLE
Icon Request: Logo for other media houses

### ISSUE THREAD

**Issue by eirikbacker** [nrkno/core-icons#42]
Requested by @mariuslundgard

**Comment by formfett** [comment]
Er det innafor at vi har logoen til TV2 i vårt ikonsett? Er det noe som skal brukes mange steder?

**Comment by eirikbacker** [comment]
true that, what cases and what specific logos do we use a lot for others? core-icons should not grow too much :)

**Comment by eirikbacker** [comment]
should I close this @mariuslundgard ?
