### ISSUE TITLE
Icon Request: Poll

### ISSUE THREAD

**Issue by oyvindjohannessen** [nrkno/core-icons#43]
We need an icon on our front page to indicate polls, voting and such.
Here it is https://www.dropbox.com/s/38izq66jmswujzu/nrk-poll.svg?dl=0

**Comment by eirikbacker** [comment]
[nrk-poll.svg.zip](https://github.com/nrkno/core-icons/files/2084550/nrk-poll.svg.zip)
Ny versjon fra magnus

**Comment by eirikbacker** [comment]
Justert til 15x15
```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 15 15">
  <rect x="2.5" y="8" width="2" height="5" rx="1"></rect>
  <rect x="6.5" y="3" width="2" height="10" rx="1"></rect>
  <rect x="10.5" y="5" width="2" height="8" rx="1"></rect>
</svg>
```

**Comment by oyvindjohannessen** [comment]
Kjør på!
