### ISSUE TITLE
Public NPM package

### ISSUE THREAD

**Issue by jesperstarkar** [nrkno/core-icons#45]
This repo is public but the current NPM package is private to NRK. Would you consider opening the NPM package, or should we fork to solve this ourselves?

**Comment by eirikbacker** [comment]
@jesperstarkar Well spotted! The NPM repo is now also public - NRK <3 Open Source :)

**Comment by jesperstarkar** [comment]
Perfect! The NRK Project prefixes tv-automation- (14 repos under MIT) on @nrkno is depending on this. Reuse ftw!
