### ISSUE TITLE
Icon Request: 

### ISSUE THREAD

**Issue by oyvindjohannessen** [nrkno/core-icons#46]
**DURATIUON**
We need an icon to indicate duration, primarily used for short videos and on demand video
https://www.dropbox.com/s/yldhv3q0waxh2w7/nrk-duration.svg?dl=0

**DURATIUON**
We need an icon to indicate a hyperlink, primarily used in the context of sharing to SoMe, to let the user decide how to share the link for them self
https://www.dropbox.com/s/8z906anhcqbkzvm/nrk-link.svg?dl=0

**Comment by eirikbacker** [comment]
Resolved by #47
