### ISSUE TITLE
Icon request: Categories

### ISSUE THREAD

**Issue by eirikbacker** [nrkno/core-icons#48]
From Helene
```
<svg viewBox="0 0 15 15" xmlns="http://www.w3.org/2000/svg">
  <path d="M13.47 6.31l1.43.72a.17.17 0 0 1 0 .31l-7.26 3.72c-.09.04-.2.04-.28 0L.1 7.34a.17.17 0 0 1 0-.3l1.43-.73 1.02.44-.54.29c-.03.01-.13.08-.13.12 0 .1.05.1.13.13L7.28 10c.14.07.3.07.44 0l5.25-2.66.13-.08c.04-.03.05-.06.05-.08 0-.05-.09-.09-.18-.14l-.59-.29 1.09-.44z M13.47 9.22l1.43.72a.17.17 0 0 1 0 .3l-7.26 3.73c-.09.04-.2.04-.28 0L.1 10.25a.17.17 0 0 1 0-.31l1.43-.72 1.02.44-.54.28c-.03.02-.13.09-.13.13 0 .09.05.09.13.13l5.27 2.71c.14.07.3.07.44 0l5.25-2.66.13-.08c.04-.03.05-.06.05-.08 0-.05-.09-.1-.18-.15l-.59-.28 1.09-.44zM7.8 1.07l7.1 3.37a.17.17 0 0 1 0 .3L7.64 8.16c-.09.04-.2.04-.28 0L.1 4.75a.17.17 0 0 1 0-.31l7.1-3.37c.2-.1.4-.1.6 0zm-.1.86c-.17-.08-.2-.08-.36 0a433.32 433.32 0 0 1-5.2 2.52.16.16 0 0 0 0 .28L7.3 7.16c.13.05.23.05.35 0l5.12-2.4c.06-.01.1-.04.12-.06.05-.05.05-.1.05-.11 0-.02 0-.1-.17-.17L7.7 1.92z"/>
</svg>
```

**Comment by eirikbacker** [comment]
Unsure if this is `nrk-media-categories` or `nrk-categories`. Any thoughts @formfett / Øyvind ?

**Comment by eirikbacker** [comment]
Cool, just poke me whenever you're ready to roll @oyvindjohannessen

**Comment by formfett** [comment]
Bra, @oyvindjohannessen 👍
Kult om vi har ett ikon som kan brukes på tvers.
Kanskje se på et nytt ikon som kan funke over alt? Ikonet i NRK.no appen er vel mer en representasjon av hvordan siden ser ut, enn hva brukerbehovet for valget er, eller "hva en kategori er".

**Comment by oyvindjohannessen** [comment]
Rutenett-ikonet er ganske mye brukt rundt omkring, ref https://thenounproject.com/search/?q=categories

Øyvind Johannessen
Designer, nrk.no<http://nrk.no>-utvikling
Medieutvikling
Mobil: +47 93004362

27. jun. 2018 kl. 15:16 skrev Magnus Cederholm <notifications@github.com<mailto:notifications@github.com>>:


Bra, @oyvindjohannessen<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Foyvindjohannessen&data=01%7C01%7Coyvind.johannessen%40nrk.no%7Cd957d06c33324318456a08d5dc30383e%7C9d2ac018e8434e149e2b4e0ddac75450%7C1&sdata=gVxRQM8lHHAhpVPPYLlpiXma8Roy6LdifsCdWUFm3KY%3D&reserved=0> 👍
Kult om vi har ett ikon som kan brukes på tvers.
Kanskje se på et nytt ikon som kan funke over alt? Ikonet i NRK.no<http://NRK.no> appen er vel mer en representasjon av hvordan siden ser ut, enn hva brukerbehovet for valget er, eller "hva en kategori er".

**Comment by eirikbacker** [comment]
Final icon
```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 15 15">
  <path d="M2 2v4h4V2H2zm-.6-1h5.2c.2 0 .4.2.4.4v5.2c0 .2-.2.4-.4.4H1.4a.4.4 0 0 1-.4-.4V1.4c0-.2.2-.4.4-.4zM9 2v4h4V2H9zm-.6-1h5.2c.2 0 .4.2.4.4v5.2c0 .2-.2.4-.4.4H8.4a.4.4 0 0 1-.4-.4V1.4c0-.2.2-.4.4-.4zM2 9v4h4V9H2zm-.6-1h5.2c.2 0 .4.2.4.4v5.2c0 .2-.2.4-.4.4H1.4a.4.4 0 0 1-.4-.4V8.4c0-.2.2-.4.4-.4zM9 9v4h4V9H9zm-.6-1h5.2c.2 0 .4.2.4.4v5.2c0 .2-.2.4-.4.4H8.4a.4.4 0 0 1-.4-.4V8.4c0-.2.2-.4.4-.4z"/>
</svg>
```
