### ISSUE TITLE
Icon request: Comment / dialog

### ISSUE THREAD

**Issue by eirikbacker** [nrkno/core-icons#49]
Forslag; bruke:
![image](https://user-images.githubusercontent.com/691801/42032147-efb7ae58-7ad8-11e8-89a3-ca38156030f5.png)

**Comment by eirikbacker** [comment]
Previous chat icon. Maybe you want to do some adjustments @formfett ? :)
[Chat Icon.sketch.zip](https://github.com/nrkno/core-icons/files/2147840/Chat.Icon.sketch.zip)

**Comment by formfett** [comment]
Da jeg så på dette sist så la jeg til en snakkeboble til for at det skal skille seg litt mer fra subtitles.
Blir det mindre tydelig at det er chat da? Blir jo mer kommunikasjon mellom flere …

<img width="178" alt="screen shot 2018-06-29 at 09 01 15" src="https://user-images.githubusercontent.com/8984470/42077964-02b5369a-7b7b-11e8-83a2-9b568a089004.png">

**Comment by eirikbacker** [comment]
er det nødvendig å skille på chat og discussion? tenker `nrk-discussion` er flott jeg - dialog er bra, og litt mer organisk form skiller fra teksting og menneskeliggjør det. Hva tenker du @Isdoda ? :)

**Comment by eirikbacker** [comment]
legger du ved `nrk-discussion` @formfett , så kan jeg gjør klar for publish om folk er enig?

**Comment by eirikbacker** [comment]
@formfett er det mulig å få laget både `nrk-dicussion` (2 bobler) og `nrk-comment` (1 boble - må trolig lage litt tydeligere spiss og skalere opp). Har pratet med Ida :)
