### ISSUE TITLE
Icon Request: more-icon?

### ISSUE THREAD

**Issue by eirikbacker** [nrkno/core-icons#61]
Origo Styleguide har i dag et 3-dottet ikon for "mer"
```
<svg viewBox="0 0 20 20"><path d="M5,10A2,2,0,1,1,3,8,2,2,0,0,1,5,10Zm5-2a2,2,0,1,0,2,2A2,2,0,0,0,10,8Zm7,0a2,2,0,1,0,2,2A2,2,0,0,0,17,8Z" /></svg>
```
dette er trolig ønskelig å bruke i NRK.no (i stede for tekst+chevron slik vi bruker til dropdowns i dag). Konvensjon vi ønsker å bruke i andre produkter også? mobil? Tv/Radio? Eksempel på bruk i dele-dialog:
![redezign_videorom_m_deling](https://user-images.githubusercontent.com/691801/44328899-2e482e00-a463-11e8-8650-502ce8881971.jpg)

**Comment by eirikbacker** [comment]
Not needed: better to use more contextually communicating icons. This case was solved by new share-icon

**Comment by formfett** [comment]
Trenger more-ikon allikevel, på NRK TV.
Vedlagt ferdig ikon her:
[more.svg.zip](https://github.com/nrkno/core-icons/files/3197554/more.svg.zip)
