### ISSUE TITLE
Add 'base64' download option

### ISSUE THREAD

**Issue by popeindustries** [nrkno/core-icons#72]
Add a link for each Icon to download as base64 for pasting as inline css

**Comment by eirikbacker** [comment]
We do not really want to encourage this usage, the only real example of this is inlining the `nrk-chevron-right` icon as `list-style`. Maybe just add an example with this in the docs instead? :)

**Comment by popeindustries** [comment]
I’m not sure it’s up to us to encourage/discourage, but ok

**Comment by eirikbacker** [comment]
Well, you're right - we do not want SVG primarily inlined, but it is nice to have some times. Let's add "Copy CSS" option, and use the logic from here https://github.com/yoksel/url-encoder/
