### ISSUE TITLE
Update a11y docs: simpler non-clickable markup

### ISSUE THREAD

**Issue by eirikbacker** [nrkno/core-icons#77]
Markup described in non-clickable section in https://static.nrk.no/core-icons/latest/index.html#accessibility is no longer needed - can be simplified to:

```
Hide the icon from screen readers with aria-hidden="true", and add screen reader content to a wrapper with role="img" aria-label="…"
```
(aka without <span class="nrk-sr">)

and markup is
```
<span role="img" aria-label="Terningkast seks">
  <svg aria-hidden="true" style="width:1.5em;height:1.5em;vertical-align:middle"><use xlink:href="#nrk-dice-6--active"></use></svg>
</span>
Fantastisk!
```

**Comment by htor** [comment]
should we change section in the core-css as well?

**Comment by eirikbacker** [comment]
No, thats not the same guidelines there :)
