### ISSUE TITLE
Possibly module/main package.json for core-icons.jsx too

### ISSUE THREAD

**Issue by eirikbacker** [nrkno/core-icons#85]
I dag finns `core-icons.jsx` og `core-icons-commonjs.jsx` som gjør at konsumenten må selv finne ut hva som skal konsumeres (avhengig av om man kjører på node uten bygging, eller klient med webpack/rollup/etc bygging). Forslag:
- Lage en mappe `lib/jsx`
- Legge en `package.json` uten pakkenavn inni der, med `main` og `module` felt
- Disse feltene peker til `index.js` og `index.mjs` i mappen, med tilhørende `module.export`/`export`
- Teste at dette virker både på node, med webpack og rollup

Dette blir breaking change - ny konsumering av jsx går fra:
`import {NrkLogoNrk} from '@nrk/core-icons/core-icons.jsx'`
til
`import {NrkLogoNrk} from '@nrk/core-icons/jsx'`

**Comment by htor** [comment]
resolved in #87
