### ISSUE TITLE
some icons don't adapt color

### ISSUE THREAD

**Issue by htor** [nrkno/core-icons#98]
some icons are missing stroke="currentColor" or fill="currentColor" and don't adapt:

<img width="383" alt="image" src="https://user-images.githubusercontent.com/1709263/55412359-8d2c6480-5567-11e9-9305-209dc3349871.png">

is it required to inline those attributes in the SVG to fix this?

**Comment by eirikbacker** [comment]
Well spotted. This happens due to core-docs not relying on CoreCSS anymore, and CoreCSS fixes SVG color inheritance. This could be inlined in the files, to prevent any dependencies, but have for now added a section about color instead in the docs.
